# Generated by Django 4.1.6 on 2023-02-07 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_alter_customer_mobile_alter_customer_phone"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="event_status",
        ),
        migrations.AddField(
            model_name="contract",
            name="event",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.event",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="event_closed",
            field=models.BooleanField(default=False),
        ),
    ]
