# Generated by Django 4.1.6 on 2023-02-08 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_remove_event_event_status_contract_event_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="contract",
            old_name="status",
            new_name="signed",
        ),
    ]
