# Generated by Django 4.1.6 on 2023-02-09 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_rename_status_contract_signed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="attendees",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="event_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
