# Generated by Django 4.1.6 on 2023-02-12 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_alter_event_attendees_alter_event_event_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="event_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
