# Generated by Django 4.1.6 on 2023-02-14 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_alter_event_event_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contract",
            name="event",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.event",
            ),
        ),
    ]
